name: Pull request
# This workflow is triggered on pushes to the repository.
on: [ pull_request ]

jobs:
  check:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # A PR should not contain too many commits
          fetch-depth: 10
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/download/v0.6.4/convco-ubuntu.zip -o convco-ubuntu.zip
          echo "2d09c55e78d27925dababce6c12398c57dae8b05  convco-ubuntu.zip" | sha1sum -c
          zcat convco-ubuntu.zip > convco
          chmod +x convco
          ./convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          rm convco convco-ubuntu.zip

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt